spring:
  application:
    name: boardmate

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본값: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

springdoc:
  swagger-ui:
    persist-authorization: true
    doc-expansion: none

logging:
  level:
    root: INFO
  file:
    name: /app/logs/spring.log
